# Generated by Django 3.1.5 on 2021-01-26 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210126_2152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
